question_data = [{"type": "multiple", "difficulty": "medium", "category": "History",
                  "question": "In what year did Kentucky become the 15th state to join the union?",
                  "correct_answer": "1792", "incorrect_answers": ["1782", "1798", "1788"]},
                 {"type": "multiple", "difficulty": "medium", "category": "Science &amp; Nature",
                  "question": "Which of the following spacecraft never touched the moon?",
                  "correct_answer": "Mariner 4",
                  "incorrect_answers": ["Apollo 11", "Luna 2", "SMART-1"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
                  "question": "In the Super Mario series, the character Pauline is a Princess "
                              "like Princess Peach.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "multiple", "difficulty": "medium",
                  "category": "Entertainment: Video Games",
                  "question": "Who voices Max Payne in the 2001 game &quot;Max Payne&quot;?",
                  "correct_answer": "James McCaffrey",
                  "incorrect_answers": ["Sam Lake", "Troy Baker", "Hideo Kojima"]},
                 {"type": "multiple", "difficulty": "medium", "category": "Mythology",
                  "question": "Which of these Roman gods doesn&#039;t have a counterpart in Greek "
                              "mythology?",
                  "correct_answer": "Janus", "incorrect_answers": ["Vulcan", "Juno", "Mars"]},
                 {"type": "multiple", "difficulty": "easy", "category": "Science: Computers",
                  "question": "What does CPU stand for?",
                  "correct_answer": "Central Processing Unit",
                  "incorrect_answers": ["Central Process Unit", "Computer Personal Unit",
                                        "Central Processor Unit"]},
                 {"type": "multiple", "difficulty": "medium", "category": "Geography",
                  "question": "What African country has Portuguese as its official language?",
                  "correct_answer": "Mozambique",
                  "incorrect_answers": ["Botswana", "Gabon", "Togo"]},
                 {"type": "multiple", "difficulty": "medium", "category": "Science &amp; Nature",
                  "question": "Which of these is NOT a part of the structure of a typical neuron?",
                  "correct_answer": "Islets of Langerhans",
                  "incorrect_answers": ["Node of Ranvier", "Schwann cell", "Myelin sheath"]},
                 {"type": "multiple", "difficulty": "hard",
                  "category": "Entertainment: Video Games",
                  "question": "In &quot;Call Of Duty: Zombies&quot;, which weapon does NOT deal "
                              "any damage?",
                  "correct_answer": "31-79 JGb215",
                  "incorrect_answers": ["Sliquifier", "V-R11", "Wunderwaffe DG-2"]},
                 {"type": "multiple", "difficulty": "medium",
                  "category": "Entertainment: Video Games",
                  "question": "Who composed the soundtrack for the game VVVVVV?",
                  "correct_answer": "Magnus P&aring;lsson",
                  "incorrect_answers": ["Terry Cavanagh", "Danny Baranowsky", "Joel Zimmerman"]}
                 ]
